server:
  http_listen_port: 3100

positions:
  filename: /tmp/loki-positions.json

clients:
  - url: http://loki:3100/api/prom/push

scrape_configs:
  - job_name: 'microservices'
    static_configs:
      - targets: ['categoria-meme', 'meme', 'usuario']
        labels:
          job: 'microservices'
          __path__: /var/log/*.log
