server:
  http_listen_port: 3100

positions:
  filename: /tmp/loki-positions.json

clients:
  - url: http://loki:3100/api/prom/push

scrape_configs:
  - job_name: 'categoria-meme'
    static_configs:
      - targets:
          - localhost
        labels:
          job: 'categoria-meme'
          __path__: /var/log/categoria-meme/*.log

  - job_name: 'meme'
    static_configs:
      - targets:
          - localhost
        labels:
          job: 'meme'
          __path__: /var/log/meme/*.log

  - job_name: 'usuario'
    static_configs:
      - targets:
          - localhost
        labels:
          job: 'usuario'
          __path__: /var/log/usuario/*.log
