global:
  scrape_interval: 15s  # Frequência de coleta das métricas

scrape_configs:
  - job_name: 'categoria-meme'
    static_configs:
      - targets: ['categoria-meme:8081']  # Nome do serviço 'CategoriaMeme' no Docker
    metrics_path: '/actuator/prometheus'
  - job_name: 'meme'
    static_configs:
      - targets: ['meme:8082']
  - job_name: 'usuario'
    static_configs:
      - targets: [ 'usuario:8083' ]

